//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYTECH.DL.DM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BodytechEntities : DbContext
    {
        public BodytechEntities()
            : base("name=BodytechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EVENTOS_SISTEMA> EVENTOS_SISTEMA { get; set; }
        public virtual DbSet<HISTORIAL_ACTIVIDAD> HISTORIAL_ACTIVIDAD { get; set; }
        public virtual DbSet<LISTA_BLANCA> LISTA_BLANCA { get; set; }
        public virtual DbSet<MOTIVO> MOTIVO { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<TABLA_CLIENTE> TABLA_CLIENTE { get; set; }
        public virtual DbSet<TABLETA> TABLETA { get; set; }
        public virtual DbSet<VISITAS> VISITAS { get; set; }
    }
}
