//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYTECH.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS_SISTEMA
    {
        public int ID_EVENTO { get; set; }
        public string EVENTO_DESCRIPCION { get; set; }
        public System.DateTime EVENTO_FECHA { get; set; }
    }
}
