//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYTECH.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_ACTIVIDAD
    {
        public int ID_ACTIVIDAD { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_SEDE { get; set; }
        public Nullable<System.DateTime> HORA_ENTRADA { get; set; }
        public Nullable<System.DateTime> HORA_SALIDA { get; set; }
        public Nullable<int> ID_TABLETA_ENTRADA { get; set; }
        public Nullable<int> ID_TABLETA_SALIDA { get; set; }
        public string ACTIVIDAD_REALIZADA { get; set; }
    
        public virtual SEDE SEDE { get; set; }
        public virtual TABLA_CLIENTE TABLA_CLIENTE { get; set; }
        public virtual TABLETA TABLETA { get; set; }
        public virtual TABLETA TABLETA1 { get; set; }
    }
}
