//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYTECH.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_BLANCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_BLANCA()
        {
            this.TABLA_CLIENTE = new HashSet<TABLA_CLIENTE>();
        }
    
        public int ID_LISTA { get; set; }
        public string PERSONA_ID { get; set; }
        public string PERSONA_DOCUMENTO { get; set; }
        public string PERSONA_NOMBRE { get; set; }
        public string PERSONA_GENERO { get; set; }
        public System.DateTime PERSONA_CUMPLE { get; set; }
        public int PRODUCTO_ID { get; set; }
        public string PRODUCTO_NOMBRE { get; set; }
        public string PRODUCTO_TIPO { get; set; }
        public int PRODUCTO_CANTIDAD_DISPONIBLE { get; set; }
        public System.DateTime PRODUCTO_FECHA_INICIA { get; set; }
        public System.DateTime PRODUCTO_FECHA_VENCE { get; set; }
        public int PRODUCTO_CATEGORIA_ID { get; set; }
        public string PRODUCTO_CATEGORIA_NOMBRE { get; set; }
        public int ID_ESTADO { get; set; }
        public int ID_SEDE_COMPRA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLA_CLIENTE> TABLA_CLIENTE { get; set; }
    }
}
