//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BODYTECH.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VISITAS()
        {
            this.TABLA_CLIENTE = new HashSet<TABLA_CLIENTE>();
        }
    
        public int ID_VISITA { get; set; }
        public string PERSONA_DOCUMENTO { get; set; }
        public string PERSONA_NOMBRE { get; set; }
        public System.DateTime PRODUCTO_FECHA_INICIO { get; set; }
        public System.DateTime PRODUCTO_FECHA_VENCIMIENTO { get; set; }
        public int ID_MOTIVO { get; set; }
        public string DETALLE { get; set; }
        public string EMPLOYEE_DOCUMENTO { get; set; }
    
        public virtual MOTIVO MOTIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLA_CLIENTE> TABLA_CLIENTE { get; set; }
    }
}
